export const InjectionTokens = {
  Databases: {
    Drizzle: Symbol("Database"),
    DrizzleExecutor: Symbol("DrizzleExecutor"),
    Valkey: Symbol("ValkeyClient"),
    UnitOfWork: Symbol("UnitOfWork"),
  },

  Cache: {
    Repository: Symbol("CacheRepository"),
    Account: Symbol("AccountCacheRepository"),
    AccountRole: Symbol("AccountRoleCacheRepository"),
    WorkspaceMember: Symbol("WorkspaceMemberCacheRepository"),
    WorkspaceInvite: Symbol("WorkspaceInviteCacheRepository"),
  },

  Repositories: {
    Account: Symbol("AccountRepository"),
    Token: Symbol("TokenRepository"),
    AccessToken: Symbol("AccessTokenRepository"),
    AccountRole: Symbol("AccountRoleRepository"),
    Workspace: Symbol("WorkspaceRepository"),
    WorkspaceMember: Symbol("WorkspaceMemberRepository"),
    WorkspaceInvite: Symbol("WorkspaceInviteRepository"),
    Notification: Symbol("NotificationRepository"),
    Board: Symbol("BoardRepository"),
    Column: Symbol("ColumnRepository"),
    Card: Symbol("CardRepository"),
  },

  Email: {
    Gateway: Symbol("EmailGateway"),
  },

  Storage: {
    Gateway: Symbol("StorageGateway"),
    Lifecycle: Symbol("StorageLifecycle"),
  },

  Gateways: {
    Cryptograph: Symbol("CryptographGateway"),
    PasswordHasher: Symbol("PasswordHasherGateway"),
    SendWelcomeEmail: Symbol("SendWelcomeEmailGateway"),
    TokenGenerator: Symbol("TokenGeneratorGateway"),
  },

  Consumers: {
    AccountCreated: Symbol("AccountCreatedConsumer"),
    WorkspaceInviteCreated: Symbol("WorkspaceInviteCreatedConsumer"),
    WorkspaceInviteAccepted: Symbol("WorkspaceInviteAcceptedConsumer"),
    WorkspaceInviteRejected: Symbol("WorkspaceInviteRejectedConsumer"),
  },

  Bus: {
    Command: Symbol("CommandBus"),
    Query: Symbol("QueryBus"),
  },

  Queue: {
    Client: Symbol("RabbitMQClient"),
    Publisher: Symbol("QueuePublisher"),
    ConsumerRegistry: Symbol("ConsumerRegistry"),
    DeadLetterConsumer: Symbol("DeadLetterConsumer"),
    DeadLetterRepository: Symbol("DeadLetterRepository"),
    OutboxRepository: Symbol("OutboxRepository"),
    OutboxRelay: Symbol("OutboxRelay"),
  },

  Handlers: {
    Authenticate: Symbol("AuthenticateHandler"),
    Logout: Symbol("LogoutHandler"),
    RefreshToken: Symbol("RefreshTokenHandler"),
    CreateAccount: Symbol("CreateAccountHandler"),
    GetAccount: Symbol("GetAccountHandler"),
    SendWelcomeEmail: Symbol("SendWelcomeEmailHandler"),
    CreateWorkspace: Symbol("CreateWorkspaceHandler"),
    GetWorkspace: Symbol("GetWorkspaceHandler"),
    UpdateWorkspaceAvatar: Symbol("UpdateWorkspaceAvatarHandler"),
    ListWorkspaceMembers: Symbol("ListWorkspaceMembersHandler"),
    ListMyWorkspaces: Symbol("ListMyWorkspacesHandler"),
    GetMyMembership: Symbol("GetMyMembershipHandler"),
    RemoveWorkspaceMember: Symbol("RemoveWorkspaceMemberHandler"),
    UpdateWorkspaceMemberRole: Symbol("UpdateWorkspaceMemberRoleHandler"),
    InviteMember: Symbol("InviteMemberHandler"),
    RespondToInvite: Symbol("RespondToInviteHandler"),
    ListWorkspaceInvites: Symbol("ListWorkspaceInvitesHandler"),
    ListMyInvites: Symbol("ListMyInvitesHandler"),
    CreateNotification: Symbol("CreateNotificationHandler"),
    MarkNotificationAsRead: Symbol("MarkNotificationAsReadHandler"),
    MarkAllNotificationsAsRead: Symbol("MarkAllNotificationsAsReadHandler"),
    ListNotifications: Symbol("ListNotificationsHandler"),
    CreateBoard: Symbol("CreateBoardHandler"),
    RenameBoard: Symbol("RenameBoardHandler"),
    DeleteBoard: Symbol("DeleteBoardHandler"),
    ListWorkspaceBoards: Symbol("ListWorkspaceBoardsHandler"),
    GetBoard: Symbol("GetBoardHandler"),
    CreateColumn: Symbol("CreateColumnHandler"),
    MoveColumn: Symbol("MoveColumnHandler"),
    DeleteColumn: Symbol("DeleteColumnHandler"),
    CreateCard: Symbol("CreateCardHandler"),
    UpdateCard: Symbol("UpdateCardHandler"),
    MoveCard: Symbol("MoveCardHandler"),
    AssignCard: Symbol("AssignCardHandler"),
    DeleteCard: Symbol("DeleteCardHandler"),
  },

  Controllers: {
    CreateAccount: Symbol("CreateAccountController"),
    Authenticate: Symbol("AuthenticateController"),
    RefreshToken: Symbol("RefreshTokenController"),
    Logout: Symbol("LogoutController"),
    GetMe: Symbol("GetMeController"),
    CreateWorkspace: Symbol("CreateWorkspaceController"),
    GetWorkspace: Symbol("GetWorkspaceController"),
    UpdateWorkspaceAvatar: Symbol("UpdateWorkspaceAvatarController"),
    ListWorkspaceMembers: Symbol("ListWorkspaceMembersController"),
    ListMyWorkspaces: Symbol("ListMyWorkspacesController"),
    GetMyWorkspaceMembership: Symbol("GetMyWorkspaceMembershipController"),
    RemoveWorkspaceMember: Symbol("RemoveWorkspaceMemberController"),
    UpdateWorkspaceMemberRole: Symbol("UpdateWorkspaceMemberRoleController"),
    InviteMember: Symbol("InviteMemberController"),
    RespondToInvite: Symbol("RespondToInviteController"),
    ListWorkspaceInvites: Symbol("ListWorkspaceInvitesController"),
    ListMyInvites: Symbol("ListMyInvitesController"),
    ListNotifications: Symbol("ListNotificationsController"),
    MarkNotificationAsRead: Symbol("MarkNotificationAsReadController"),
    MarkAllNotificationsAsRead: Symbol("MarkAllNotificationsAsReadController"),
    CreateBoard: Symbol("CreateBoardController"),
    RenameBoard: Symbol("RenameBoardController"),
    DeleteBoard: Symbol("DeleteBoardController"),
    ListWorkspaceBoards: Symbol("ListWorkspaceBoardsController"),
    GetBoard: Symbol("GetBoardController"),
    CreateColumn: Symbol("CreateColumnController"),
    MoveColumn: Symbol("MoveColumnController"),
    DeleteColumn: Symbol("DeleteColumnController"),
    CreateCard: Symbol("CreateCardController"),
    UpdateCard: Symbol("UpdateCardController"),
    MoveCard: Symbol("MoveCardController"),
    AssignCard: Symbol("AssignCardController"),
    DeleteCard: Symbol("DeleteCardController"),
  },

  Middlewares: {
    ErrorHandler: Symbol("ErrorHandlerMiddleware"),
    Auth: Symbol("AuthMiddleware"),
    Authorize: Symbol("AuthorizeMiddleware"),
    ValidateWorkspace: Symbol("ValidateWorkspaceMiddleware"),
    FileUpload: Symbol("FileUploadMiddleware"),
    Pagination: Symbol("PaginationMiddleware"),
    RateLimit: Symbol("RateLimitMiddleware"),
    Idempotency: Symbol("IdempotencyMiddleware"),
    Logger: Symbol("LoggerMiddleware"),
    Tracing: Symbol("TracingMiddleware"),
    Metrics: Symbol("MetricsMiddleware"),
    InternalToken: Symbol("InternalTokenMiddleware"),
    ResolveBoardWorkspace: Symbol("ResolveBoardWorkspaceMiddleware"),
  },
} as const;
